name: Run spec tests on Gnosis

# defaults:
#   run:
#     shell: zsh {0}

env:
  TEST_PRESET_TYPE: "gnosis"

on:
  # push:
  #   branches:
  #     - gnosis
  pull_request:
  workflow_dispatch:
    inputs:
      test_preset_type:
        default: gnosis
        description: Type of test to run, either mainnet or minimal
        type: string
        required: true
  # schedule:
  #   - cron: '0 5 * * *'

jobs:
  table_of_contents:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: ''
      - name: Check table of contents
        run: npm install -g doctoc@2.2.0 && make check_toc


  pyspec-tests:
    runs-on: ubuntu-latest
    needs: [table_of_contents]
    strategy:
      fail-fast: false
      matrix:
        version: ["phase0", "altair", "bellatrix", "capella", "deneb", "electra", "whisk", "eip7594"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust for dependencies
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.4'
          cache: ''
      - name: set TEST_PRESET_TYPE
        if: github.event.inputs.test_preset_type != ''
        run: |
          echo "spec_test_preset_type=${{ github.event.inputs.test_preset_type || env.TEST_PRESET_TYPE }}" >> $GITHUB_ENV
      - name: set TEST_PRESET_TYPE
        if: ${{ (github.event_name == 'push' && github.ref_name != 'gnosis') || github.event_name == 'pull_request' }}
        run: |
          echo "spec_test_preset_type=${{ env.TEST_PRESET_TYPE}}" >> $GITHUB_ENV
      - name: set TEST_PRESET_TYPE
        if: ${{ github.event_name == 'push' && github.ref_name == 'gnosis' }}
        run: |
          echo "spec_test_preset_type=gnosis" >> $GITHUB_ENV
      - name: set TEST_PRESET_TYPE
        if: github.event.schedule=='0 0 * * *'
        run: |
          echo "spec_test_preset_type=gnosis" >> $GITHUB_ENV
      - name: Install pyspec requirements
        run: make install_test
      - name: test-${{ matrix.version }}
        continue-on-error: true
        run: make citest fork=${{ matrix.version }} TEST_PRESET_TYPE=${{env.spec_test_preset_type}}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports-${{ matrix.version }}
          path: tests/core/pyspec/test-reports

  gen-modcheck:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.4'
          cache: ''
      - name: Install pyspec requirements
        run: make install_test
      - name: Run generators with --modcheck
        run: make generate_tests modcheck=true
